### PR TITLE
UI updated, new components, fix games load

### PR DESCRIPTION
**Pull request by jwallet**
## Calendar component
- Custom navigation buttons (from Google Icons), buttons are now images and their color change on mouse hover, they were added in the project resources
- New Calendar component that looks like metro theme and also like NHL Game Center Live website
- Display a date like Sun, Apr 16, 2017 instead of 04/16/17, to looks like NHL Game Center Live website.
- Disable buttons Yesterday, Tomorrow and Calendar when Games are loading, to prevent getting more than one day in the flowLayoutPanel (one request at a time), refresh button is still active tho (close issue #38)
- Display a 'No games found' if there is no games that day, so we know that it did try to find something
- Status bar changed a bit to fit with the theme, and I made the status text permanent, because there is no need to hide it
- Display a progress bar when the app is searching for games
- Tooltips on stream qualities in settings

## Game component
- Added an option to show/hide live scores
- Added an alert if no stream is available for a game
- Time of a game will be set to 'Final' when the game is over
- If the game ends in OT, OT will be added to lblState "Final/OT"
- Different border colors shows the status of a game
    - Gray , scheduled game (tomorrow or >)
    - Metro Blue, tonight's games (upcoming)
    - Green, Pregame
    - Red, Live, In progress
    - None, past games
- Added label for offseason game
    - before season = Preseason
    - after season = Playoffs
- Playoffs
   - Show game number for a serie (game 3)
   - Show game status for a serie (TOR leads 2-0)
       - if Show Scores is unchecked it will display "Playoffs"
- Renamed all logos to keep only team names, this is to fix "Coyotes" not being displayed when looking at old games when they were named "Phoenix Coyotes" (close issue #43)
- Added Vegas Golden Knights logo
- Tooltips on streams

close issue #38
close issue #43
close issue #14 (tried 125% and 150%, and UI looked good)

image

### CODE REVIEW

**Comment by jwallet** [comment]
tested on larger font scale 150%. windows to make it fit, so now lbldate is a bit smaller

image

**Comment by jwallet** [comment]
Preseason & no stream alert (without scores) |-------| Season (with scores)
image image

Playoff (without scores) |-------------------------------| Playoff (with scores)
image image


Live Playoff(without live scores) |-----------------------| Live Playoff(with live scores)
image image

Pregame |-----------------------------------------------| Upcoming today's playoff game
image image

Scheduled playoff game (tomorrow or >)
image

**Comment by jwallet** [comment]
image

**Comment by NHLGames** [comment]
Wow, you've been busy!  Appreciate all the effort.  I'll have a look at these changes later today

**Comment by jwallet** [comment]
close issue #14 (tried 125% and 150%, and UI looked good)

**Pull request merged**
