### PR TITLE
v.1.1.0

### PR DESCRIPTION
**Pull request by jwallet**
v.1.1.0

I invited redditors to try this PR, this is where you can download/clone the current project
Testing/Clone repo : https://github.com/jwallet/NHLGames/tree/refact-modules

I made some breaking changes almost half of the code changed, so it needs to be tested alot before released.
Try it with different OS, different pc, media players, streamers (currently back to livestreamer, can still use streamlink), even hostname (added PowerSports.ml) and also try OBS and Spotify recoded modules

MPV and LiveStreamer folders needs to be copied in debug folder when testing the build
Open NHLGames.sln and press the green Play button

> Updated UI and game panel visual    
Updated Game fetcher (less buggy)
Ad detector moved to main app in settings   
Many bug fixes and some new options and configs    
Updated documentation

image

Change log
-----

- User Interface
   - Ad detector is now in Settings instead of Modules
   - DPI is now managed by the app, so it should not move anymore (except message box)
   - New game panel that hides spoilers better
       - spoilers hidden: game time and game status will always be displayed
       - spoilers displayed: scores and game status will be displayed
   - New toggle buttons in settings to control game panel
   - Stream qualities are now into a drop down list, so more details about the quality can be displayed.
   - Help button [?] now links to NHLGames wiki (support)
   - Others tweak to get ready for next version with the recorder scheduler
- Ad Detector v2
   - still supports the same apps : Spotify and OBS
   - auto show spotify (next song enabled) and OBS to get better control of the external app when sending command NHLGames to the external app, and auto hide once done. it is a new feature, so if does not auto hide advise me @jwallet (or @w1z1k on reddit)
   - Spotify
       - now can auto skip to next song at the beginning of each ad
       - Turning on [try with the detected media player] will control any detected media player even if spotify is not detected, like window media player. note that this feature does not work with MPC since MPC is detected as an audio player.
- Configurations
   - Enhanced hosts file code : add / remove /admin access and warning on game panels if hosts file does not work
   - Removed old hostname ChickenKiller and added PowerSports
   - New versioning, MAJOR.MINOR.BUILD.REVISION only numbers, no letters. revision should be use only in rare case (patch/hotfix). revision won't be display on UI but will be compare to next version
   - Does not save JSON files in appdata anymore, actually is not saving files at all, but  it still edits your Hosts file
   - Media players and streamer custom paths now properly save
   - First launch will be slower to verify if the app has everything ready to stream properly: hostname, ip redirection configs file and internet connection
   - when starting a game if the selected stream quality is not available, a lower quality will be selected, to prevent the stream to fail.
   - Streamlink is not the default streamer anymore (livestreamer is) but the streamer path browser still accept streamlink.exe as a streamer
   - if output (recorder) is set, it will open a command window if a stream is recording (to be able to stop the streamer whenever you want)
- External apps
   - Not using external DLL modules anymore, everything was rewritten into the main app. Ad Detector controls are now in Settings tab.
   - MPV 2.0.0 i
   - LiveStreamer is back, it's now the default streamer since StreamLink was flagged by Windows Defender. Since LiveStreamer is not updated anymore, the directory does not contains the version since version 12 is the last one.
   - Removed useless and old dependencies: Spotify-API.NET, Prims.Core, CSCore
- Many bug fixes such as:
   - Error getting streams from remote server, the games that return 404 error how now ignored and return warning in console instead of errors
   - refreshing now also updates streams links (networks)
   - Length cannot be less than zero
   - Mpv running in process but not showing
   - not trying to resolve streams that are set to MEDIA_OFF from nhl api response
   - added a warning if the stream failed to open
   - Threads converted to tasks to avoid errors in console while asking for web requests/responses (a bit slower atm)
   - Tweaked spinners, they should not appear at the same time anymore when switching between two streams
- Documentation
   - added informations about editing the Hosts file
   - support section: removed resolved issues
   - updated the whole documentation
   
Versionning: manage version in project properties under assembly infos

### CODE REVIEW

**Comment by d-kar** [comment]
I tried to build and run your branch, but for some reason if I use livestreamer it doesn't work (cmd window pops up briefly and nothing happens). When I switch to streamlink.exe then everything works.
Another issue, if I don't start in Admin mode and allow to edit hosts file in a splash screen, then nothing happens. (it used to relaunch I think with admin rights)
Other then that, looks like a great update.

**Comment by d-kar** [comment]
I think you broke something with "faster tasks" commit. It does not show now all available streams:
image

**Comment by jwallet** [comment]
can you retry livestreamer, if it does not work, can you download the zip file [here](https://github.com/chrippa/livestreamer/releases/download/v1.12.2/livestreamer-v1.12.2-win32.zip) and unzip the folder in the /bin folder , i think github does not like binaries files in the repo. so livestreamer is incomplete

**Comment by d-kar** [comment]
Yes this works.
I don't think we should keep livestreamer/streamlink or mpv in repo at all.

**Comment by jwallet** [comment]
yes i know it's not good practice at all, it was just easier for me because i used to switch computers many times during the summer, i don't think we actually release the app with those.

**Comment by NHLGames** [comment]
Great work on the new version!  Livestreamer from the repo did not work, I had to point at a previous copy of Livestreamer from an old version of NHLGames.

Do you plan on making any more changes to this version?  If not I will test some more tonight and create a new release.  This fixes a lot of issues people are running into these days.

**Comment by jwallet** [comment]
it will be ready tomorrow night I guess.
about livestreamer, if you got an older version, i guess it should still be version 1.12 since it did not change for a year. If you see a reason why streamlink should be our default, tell me, i see none. btw, the streamer path browser accepts both. also, had something in mind to add to this PR, make sure it's not in the change log, like the new hostname, it's already added

**Comment by jwallet** [comment]
Ready!

**Pull request merged**
