### PR TITLE
Add ad action delay option

### PR DESCRIPTION
**Pull request by fdarveau**
Enables customization of the delay before playing, pausing or skipping to next track in the ad detection feature.

Can fix an issue where Pause() is called twice in a row if the first one completes too early.

Replaces the hard coded 100ms delay with a default 100ms delay.

### CODE REVIEW

**Comment by fdarveau** [comment]
I am unsure about the name to use for the option, so feel free to suggest better ones.

I have fully not tested it yet, which is why I marked it as a draft.

**Comment by jwallet** [comment]
> I have not fully tested it yet, which is why I marked it as a draft.

Ad Detection 
- Delay between macro steps
- Macro action steps delay
- Delay between automated keystrokes 

It might be call twice because the app did not have the focus yet, `SetForegroundWindowFromHandle()` so it still detects sound and send another Pause(), maybe just increasing the `Thread.Sleep()` before `SetForegroundWindowFromHandle()` is enough and will be easier to name this option like `Tabing delay` or `Auto app switcher delay`

**Comment by fdarveau** [comment]
It might work for Spotify, but if another music app is used (which is my use case), we also need to change the sleep time in the other methods where there is no tabbing involved.

**Comment by fdarveau** [comment]
After a few tests, it seems to work pretty well on my end.

Would it be clearer if the option was named "Media control delay"/"Délai des contrôles de médias"? Or could this potentially be used for OBS/future plans for another ad detection plugin?

**Comment by jwallet** [comment]
no future plan for addons, this name fits the current state of the code, we will see if this option name still make sense if new addons are added

**Comment by fdarveau** [comment]
Ok. I will push the updated labels/variable names tomorrow.

**Comment by jwallet** [comment]
this is ready for testing. once one of us approves it, this will be merged

**Review by jwallet — APPROVED** [review]

**Pull request merged**
