### PR TITLE
UI Update and settings handler

### PR DESCRIPTION
**Pull request by JimmyJonesJr**
Updating UI to make things easier to maintain and pushing to logic further way from the UI.
Also adding ability to manually specify paths to exe's in case things are not in program files.

### CODE REVIEW

**Comment by d-kar** [comment]
You forgot to add NHLGamesMetro.vb
You fork is also missing it

**Comment by JimmyJonesJr** [comment]
Can you tell I'm used to TFS? :)

**Comment by NHLGames** [comment]
Wow you guys have been busy! I guess I should probably check GitHub more often ;)

**Comment by d-kar** [comment]
Wow nice ui update!
Bug found: in watch game window, when enabling 3 extra options, text fields are still disabled (like extra parameters to vlc or livestreamer)

**Comment by NHLGames** [comment]
So I'm new to GitHub and made a mistake merging somehow.  Now I don't seem to have the option to merge this pull request.  Anyone have some insight?

**Comment by JimmyJonesJr** [comment]
Not from me, I'm new to github as well. Really only use TFS these days. :(

**Comment by d-kar** [comment]
You can revert those changes, they are not important

**Comment by NHLGames** [comment]
Doesnt let me revert either since I've made some changes apparently.  Would rebasing the entire branch be a bad idea?

**Comment by JimmyJonesJr** [comment]
So I merged d-kar's changes into my pull request (I think I got them all, required more manual work than I was expecting from git to be honest). Not sure if that help you on your end or not.

**Comment by d-kar** [comment]
the Output doesn't work right now
-o option is for livestreamer, not for VLC
for VLC you need to specify like this:
"--sout file/ts:" & filename
if you want to start vlc minimized can specify this flag:
--qt-start-minimized

**Comment by NHLGames** [comment]
Ok cool.  I just manually merged everthing into master, check it out and see if everything is there (fingers crossed).  GitHub still wont let me merge this request.  If everything looks good I'll close this one.

**Comment by JimmyJonesJr** [comment]
It looks like it's just missing my last 1 or 2 commits:

https://github.com/NHLGames/NHLGames/pull/4/commits/8782347e9790a8d7c3a212636cea4722b21cb6d3 (making checkboxes work on watch game adanved options)
https://github.com/NHLGames/NHLGames/pull/4/commits/4ba7819bf95755c4df0292f1420857396bb00d8b

**Comment by NHLGames** [comment]
Integrated these commits into master branch.  Hopefully next time I won't create too many conflicts!

**Pull request closed without merging**
